services:

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.49.2
#    container_name: cadvisor
#    ports:
#      - 8080:8080
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:v3.1.0
#    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=100y
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /media/kakn/storage/prometheus:/prometheus
#    depends_on:
#      - cadvisor
